### PR TITLE
feat: Add developer quality of life changes

### PR DESCRIPTION
**Pull request by l0b0**

### CODE REVIEW

**Comment by m-mohr** [comment]
I don't think this belongs into the extension repos.

**Comment by l0b0** [comment]
> I don't think this belongs into the extension repos.

I've removed the IDEA-related configuration. How's this? The editor configuration is useful for anyone using a compatible editor, and the newline at EOF means Git shows nicer diffs.

**Comment by m-mohr** [comment]
What do you think, @emmanuelmathot ?

**Comment by emmanuelmathot** [comment]
As best practices, I have always been told that IDE or dev software related config should not be in a shared repo. Now `.editorconfig` file is a more generic file even supported by github so this may be accepted IMO.

**Pull request merged**
