### PR TITLE
Add processing:expression

### PR DESCRIPTION
**Pull request by m-mohr**
Would be great if someone could check the list of potential formats and add/improve others.

### CODE REVIEW

**Comment by emmanuelmathot** [comment]
It looks good to me. Simple but I like the idea to keep the expression open to any object. I have the feeling that this will open to many formats in the future and could require proper extensions for the expression spec.

**Review by emmanuelmathot — APPROVED** [review]

**Comment by emmanuelmathot** [comment]
How do we specify that the field can also be used in the `virtual:assets` items' fields?

**Comment by m-mohr** [comment]
Not sure what we decided for, but I think we could either go with the existing field in raster that just re-uses this definition or use processing:expression in the raster extension. The idea was to have a common building block, so both sound good to me.

**Comment by m-mohr** [comment]
From my side we can merge this... Thoughts?

**Comment by emmanuelmathot** [comment]
We can merge

**Comment by m-mohr** [comment]
Merged.

**Pull request merged**
