### PR TITLE
Add processing execution link for traceability

### PR DESCRIPTION
**Pull request by emmanuelmathot**
This PR to add a possible link to the processing itself

### CODE REVIEW

**Comment by m-mohr** [comment]
via is already used here for a different purpose:
https://github.com/radiantearth/stac-spec/blob/fd8fb4e3cf0b6c4a0fe74822accbc1725a92f92a/best-practices.md?plain=1#L650

We need to clarify how we can distinguish the use-cases.

**Comment by emmanuelmathot** [comment]
right, I forgot that one.
Maybe a dedicated link relationship should be used.
`provenance` or `origin`

**Comment by m-mohr** [comment]
What exactly would you use these links for? What are they pointing to?
How does it differentiate from `processing-expression`?

**Comment by matthewhanson** [comment]
Discussed in STAC sprint.

This would be a helpful link relation, looking for suggestions on a more appropriate name.

See https://www.iana.org/assignments/link-relations/link-relations.xhtml

**Review by m-mohr — APPROVED** [review]

**Pull request merged**
